/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candles */
        get: operations["candles_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candles Summary */
        get: operations["candles_summary_candles_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signals */
        get: operations["signals_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dca */
        get: operations["dca_dca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtests */
        get: operations["backtests_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest Trades */
        get: operations["backtest_trades_backtests__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandleOut */
        CandleOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: string;
        };
        /** CandlesSummaryOut */
        CandlesSummaryOut: {
            /**
             * First
             * Format: date-time
             */
            first: string;
            /**
             * Last
             * Format: date-time
             */
            last: string;
            /** Count */
            count: number;
        };
        /** DcaOut */
        DcaOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Close */
            close: string;
            /**
             * Next Payday
             * Format: date
             */
            next_payday: string;
            /** Days Until */
            days_until: number;
            /** Holidays Checked */
            holidays_checked: boolean;
            /** Positions */
            positions: components["schemas"]["PricePositionOut"][];
            /** Monthly */
            monthly: string;
            /** First Buy */
            first_buy: string | null;
            /** Months */
            months: number;
            /** Invested */
            invested: string;
            /** Final Value */
            final_value: string;
            /** Return On Invested */
            return_on_invested: string;
            /** Worst Vs Invested */
            worst_vs_invested: string;
            /** Average Cost */
            average_cost: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Interval
         * @enum {string}
         */
        Interval: "day" | "week" | "month";
        /** PricePositionOut */
        PricePositionOut: {
            /** Window */
            window: number;
            /** Average */
            average: string;
            /** Gap */
            gap: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Code Version */
            code_version: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Cagr */
            cagr: string;
            /** Mdd */
            mdd: string;
            /** Trades */
            trades: number;
        };
        /** SignalOut */
        SignalOut: {
            /** Strategy */
            strategy: string;
            /** Status */
            status: string;
            stance: components["schemas"]["Stance"];
            /** Reason */
            reason: string;
            /** Days */
            days: number | null;
            /** Trigger */
            trigger: string | null;
            /** Close */
            close: string;
            /** Reference */
            reference: string | null;
        };
        /** SignalsOut */
        SignalsOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Price */
            price: string | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
        };
        /**
         * Stance
         * @enum {string}
         */
        Stance: "hold" | "cash" | "breakout_wait" | "breakout_hit";
        /** TradeOut */
        TradeOut: {
            /**
             * Day
             * Format: date-time
             */
            day: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Qty */
            qty: string;
            /** Price */
            price: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    candles_candles_get: {
        parameters: {
            query?: {
                market?: string;
                interval?: components["schemas"]["Interval"];
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candles_summary_candles_summary_get: {
        parameters: {
            query?: {
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesSummaryOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_signals_get: {
        parameters: {
            query?: {
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dca_dca_get: {
        parameters: {
            query: {
                market: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DcaOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtests_backtests_get: {
        parameters: {
            query?: {
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_trades_backtests__run_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
